version: 2.1
jobs:
  compile:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Install dependencies and set up build environment
          command: |
            apt-get -y update && apt-get -y upgrade
            apt-get -y install bc build-essential axel zip curl libstdc++6 git wget gcc clang libssl-dev rsync flex bison cpio libncurses5 curl python2 python make 
            # Install lsb-release with correct package name and ensure apt-utils is present
            apt-get -y install apt-utils lsb-release || apt-get -y install apt-utils && apt-get -y install lsb-release || true
            git config --global user.name "mads2570"
            git config --global user.email "qwerty2570@live.com" 
            git config --global color.ui false
            git clone https://github.com/mads2570/RAD-8895.git
            cd RAD-8895
            bash rad.sh
            cd ..
            mkdir predator
            cd predator
            wget https://raw.githubusercontent.com/mads2570/a42-kernel/refs/heads/circleci-project-setup/build_menu 
            source build_menu
      - store_artifacts:
          path: RAD-8895/kernel.zip
          destination: kernel.zip
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
