version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install necessary packages
          command: |
            lsb_release -a
            UBUNTU_VERSION=$(lsb_release -sr)
            sudo apt-get update
            if [ "$UBUNTU_VERSION" == "22.04" ]; then
              sudo apt-get install -y git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool
            fi
      - run:
          name: Download and extract Clang
          command: |
            if [[ "$CLANG_SOURCE" == *.tar.xz ]]; then
              wget -O clang.tar.xz "$CLANG_SOURCE"
              mkdir clang-custom
              tar -C clang-custom/ -xvf clang.tar.xz --strip-components=1
            elif [[ "$CLANG_SOURCE" == *.zip ]]; then
              wget -O clang.zip "$CLANG_SOURCE"
              mkdir clang-custom
              unzip clang.zip -d clang-custom/
            fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build