version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install necessary packages
          command: |
            lsb_release -a
            UBUNTU_VERSION=$(lsb_release -sr)
            sudo apt-get update
      - run:
          name: Download and extract Clang
          command: |
            if [[ "$CLANG_SOURCE" == *.tar.xz ]]; then
              wget -O clang.tar.xz "$CLANG_SOURCE"
              mkdir clang-custom
              tar -C clang-custom/ -xvf clang.tar.xz --strip-components=1
            elif [[ "$CLANG_SOURCE" == *.zip ]]; then
              wget -O clang.zip "$CLANG_SOURCE"
              mkdir clang-custom
              unzip clang.zip -d clang-custom/
            fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build