version: 2.1
jobs:
  build-kernel:
    docker:
      - image: cimg/base:stable
    environment:
      GITHUB_WORKSPACE: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Add clang-custom to PATH
          command: |
            export PATH=$GITHUB_WORKSPACE/clang-custom/bin:$PATH
            echo "export PATH=$GITHUB_WORKSPACE/clang-custom/bin:$PATH" >> $BASH_ENV
      - run:
          name: Build Kernel
          command: |
            cd $GITHUB_WORKSPACE/device_kernel/
            if [ -z "$GCC_32" ] && [ -z "$GCC_64" ]; then
              make CC="ccache clang" O=out ARCH=arm64 $CUSTOM_CMDS $EXTRA_CMDS $DEFCONFIG_NAME
              make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 $CUSTOM_CMDS $EXTRA_CMDS
            else
              make CC="ccache clang" O=out ARCH=arm64 $CUSTOM_CMDS $EXTRA_CMDS $GCC_64 $GCC_32 $DEFCONFIG_NAME
              make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 $CUSTOM_CMDS $EXTRA_CMDS $GCC_64 $GCC_32
            fi
      - run:
          name: DNT Run Step
          command: echo "DNT step executed"
workflows:
  version: 2
  build:
    jobs:
      - build-kernel